# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Node.js Script

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Fetch Updated Variables
        run: |
          curl -s https://botspammer-backend.onrender.com/variables > data.json
          cat data.json

      - name: Run Node.js Script
      - run: npm install kahoot.js-latest
      - run: node index.js
