name: Run Bot Spammer

on:
  push:
    paths:
      - "data.json"

jobs:
  process-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Process data.json
        run: cat data.json

  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Read variables from data.json
        run: |
          VARS=$(cat data.json)
          VAR1=$(echo $VARS | jq -r .var1)
          VAR2=$(echo $VARS | jq -r .var2)
          echo "VAR1: $VAR1"
          echo "VAR2: $VAR2"

      - name: Run script
        run: node index.js
